services:
  r-ollama:
    build:
        context: .
        dockerfile: ./build/Dockerfile_Unix
    container_name: r-ollama
    image: renatosamperio/r-ollama
    ports:
      - "11435:11434"
    volumes:
      - "$HOME_PATH:/var/tmp"

## docker buildx bake -f docker-compose-cross.yml
## docker buildx bake -f docker-compose-cross.yml --push
## docker buildx bake -f docker-compose-cross.yml --print